extends SceneTree
## Headless self-check for THE WAYPOINTS — the eleven indexed circles and the
## rings that stand on them (epic `godot-test1-sc6`, child .1).
##
##   godot --headless --path . --script res://scripts/waypoint_selfcheck.gd
##
## `scripts/terrain_waypoints.gd`'s banner carries the design; this file is the
## part of it a future edit cannot slip past. Four checks, and each one guards a
## different promise the later children of the epic are built on:
##
##   1. DETERMINISM AND SHAPE. `waypoint_sites()` asked twice on one seed is
##      identical; a re-seed MOVES the road circles (they hang off the road's
##      station cache, which is pure in `run_seed`) and leaves the HQ's where it
##      was (it hangs off `tower_site()`, which is a constant); the ids at every
##      index are the same strings in the same order on every seed; and the COUNT
##      is 11 in all three worlds. The count is what makes a fixed-width
##      `waypoint_mask` possible at all — a run with seven or nine waypoints
##      renumbers every peer's found set mid-room.
##   2. NOT ONE DRAW, proved twice, because either half alone passes for the
##      wrong reason:
##        a. `terrain_waypoints.gd` carries no draw and no gradient AS TEXT
##           (`landmark_sites_selfcheck` check 4's text half — a behavioural
##           count can only speak for the chunks it sampled).
##        b. A chunk with NO site is BYTE-IDENTICAL with `spawn_waypoints` on and
##           off, right down to its crocodile positions — the half that catches a
##           draw hidden behind a helper, since one stray draw slides every body
##           in the chunk. Its two controls are the other direction: a chunk WITH
##           a site must differ in its BOXES (or the comparator is blind) and
##           must NOT differ in its crocodiles or its `obstacles` (which is the
##           "a waypoint appends no footprint" rule, measured rather than
##           asserted in a comment).
##   3. LEGALITY, over three seeds and against the SHIPPED predicates. No road
##      circle is in a river band or inside the Budapest rect; every city circle
##      is inside the rect, dry, off both `PLATEAUS`, outside every `SLOTS` disc, outside every
##      `block_wing()` it could reach and on a street line; the HQ circle is
##      outside the shell's outer wall and within 12 m of the door trigger. FOUR
##      MUTATION CONTROLS drive the same predicates with a deliberately illegal
##      point each, because "no site was wet" is also what a predicate that
##      always answers false looks like.
##   4. BUILT THROUGH `create_chunk`. Every site's chunk is generated by the
##      SHIPPED pipeline and must hold exactly one marker in group "waypoint"
##      carrying the right `index`, with a beam that exists, is a mesh and is
##      HIDDEN (this bead lights nothing — child .2 does). And through a direct
##      call: the chunk's batch grows by exactly `RING_BOX_COUNT` boxes, none of
##      them colliding, and `obstacles` does not grow at all.

## The end-of-check sentinel — see `scripts/selfcheck_sentinel.gd` for why every
## check stamps itself and the report site never prints SELFCHECK OK itself.
const Sentinel := preload("res://scripts/selfcheck_sentinel.gd")

const TERRAIN_SCRIPT: String = "res://scripts/endless_terrain.gd"
## Check 5's cast: a REAL hero, the shipped room and the shipped hub. Nothing here
## is a stub — the whole value of that check is that it drives the functions the
## game calls, in the order the game calls them (the `tower_gate_sync_selfcheck`
## discipline: through the shipped functions, never around them).
const PLAYER_SCENE: String = "res://scenes/player.tscn"
const MPManager: GDScript = preload("res://scripts/mp_manager.gd")
const WaypointHub: GDScript = preload("res://scripts/waypoint_hub.gd")
## The file check 2's text half reads. ONE entry today, and a list because the
## spawners in this project keep moving house (`landmark_sites_selfcheck`'s
## `SOURCE_SCRIPTS` learned that the hard way): a name found in none of these
## fails by name rather than passing vacuously.
const SOURCE_SCRIPTS: Array[String] = [
	"res://scripts/terrain_waypoints.gd",
]
const CROC_SCENE: String = "res://scenes/characters/piglet_crocodile.tscn"

## Three seeds, the `landmark_sites_selfcheck` / `scarcity_selfcheck` set. The
## road moves with `run_seed`, so one world proves nothing about the rule and
## only about that world.
const SEEDS: Array[int] = [20260904, 777, 4242]

## Seeds check 1's cache-warmth control sweeps, in order, for the ONE shape that
## tells the two clamps apart: a WET road station within `WAYPOINT_RIVER_STEP` of
## the road's terminal. Not "a seed whose road crosses water" — road crossings are
## common (`field_bridge_selfcheck` exists for them) and every one further west is
## cleared long before either clamp binds. The sweep stops at the first seed that
## has it, so this is a SEARCH SPACE and not a sample, and the three CI `SEEDS`
## lead it only because they are cheap to try first; today it settles on seed 1.
## Widening it is the right move if the window ever goes empty — but widen it with
## that criterion, not with "a seed that has a river somewhere".
const CONTROL_SEEDS: Array[int] = [20260904, 777, 4242, 1, 424242, 999983, 750, 99, 106]

## What `waypoint_sites()` must return in every world, in order: the HQ door, its
## approach, the spawn, the road slots and the city's five. ELEVEN is the owner's
## number (2026-09-12, "10-12"), and it is written out rather than counted so
## that a row silently dropped, renamed or reordered fails BY NAME — the index is
## the wire bit, and a table that quietly renumbered would desync a room.
const EXPECTED_IDS: Array[String] = ["hq", "approach", "spawn",
		"road_1", "road_2", "road_3",
		"gate", "pest", "parliament", "market", "heroes"]

## Which of those indices are the ROAD's — the ones that must move when the seed
## does, and the ones check 3 holds out of the water and out of the city rect.
const ROAD_FIRST: int = 1
const ROAD_LAST: int = 5

## What check 2's text half refuses to find in the waypoint family. Deliberately
## NOT `RandomNumberGenerator` — `create_box` takes one by signature and the ring
## hands it a private, fixed-seed generator whose colour draws are all discarded
## (see `_build_ring`). What must not appear is a DRAW or a gradient.
const FORBIDDEN: Array[String] = ["randf", "randi", "hash(", "scarcity_at"]

## How close to the doorway the HQ circle has to stand. It is the bead's number,
## and the site is `TowerShell.OUTER_HALF + WAYPOINT_DOOR_STANDOFF` out while the
## trigger sits half a wall inside, so the real gap is ~8.6 m.
const HQ_DOOR_MAX: float = 12.0

var _failures: Array[String] = []


func _initialize() -> void:
	Sentinel.isolate_user_state()
	# The run is a coroutine because check 2 and check 4 need a terrain that is
	# really IN the tree before they build a chunk, and `_initialize()` cannot
	# await — `root.add_child()` here does not put a node in the tree yet.
	_run()


func _run() -> void:
	await process_frame
	var terrain_script: GDScript = load(TERRAIN_SCRIPT)
	_check_determinism(terrain_script)
	_check_no_draw(terrain_script)
	_check_legality(terrain_script)
	_check_built(terrain_script)
	await _check_discovery(terrain_script)

	if _failures.is_empty():
		print("waypoints: %d sites over %d seeds — stable indices, draw-free, legal, "
				% [EXPECTED_IDS.size(), SEEDS.size()]
				+ "built through create_chunk with no footprint, and found "
				+ "room-wide with the beam following the mask")
		Sentinel.finish(self)
		return
	for failure: String in _failures:
		printerr("FAIL: ", failure)
	quit(1)


func _fail(message: String) -> void:
	_failures.append(message)


func _code_only(body: String) -> String:
	"""
	`body` with its docstring and its comment lines removed, so a text assertion
	measures what the function DOES rather than what it says about itself.

	A GDScript docstring is a `\"\"\"` block; this toggles on the line that opens one
	and off on the line that closes it (a one-line `\"\"\"x\"\"\"` toggles twice and is
	dropped), then drops anything whose first non-space character is `#`. Trailing
	`#` comments on a statement line are left alone — they belong to the statement,
	and a forbidden name hiding in one is worth failing on.
	"""
	var out := ""
	var in_doc := false
	for line: String in body.split("\n"):
		var stripped := line.strip_edges()
		var fences := stripped.count("\"\"\"")
		if in_doc:
			if fences > 0:
				in_doc = false
			continue
		if fences > 0:
			in_doc = fences % 2 == 1
			continue
		if stripped.begins_with("#"):
			continue
		out += line + "\n"
	return out


func _function_body(source: String, name: String) -> String:
	"""
	The lines of `func <name>(...)` up to the next top-level `func` — the crude
	reader `landmark_sites_selfcheck` and `scarcity_selfcheck` both use, and for the
	same reason: GDScript's one-function-per-column-0-`func` layout is the whole
	grammar this needs. It matches `static func` too, which is not optional here —
	every function in `terrain_waypoints.gd` is static, and a reader that only knew
	`func ` would return "" and pass for the wrong reason.
	"""
	var out := ""
	var inside := false
	for line: String in source.split("\n"):
		if line.begins_with("func " + name + "(") \
				or line.begins_with("static func " + name + "("):
			inside = true
			continue
		if inside:
			if line.begins_with("func ") or line.begins_with("static func "):
				break
			out += line + "\n"
	return out


func _terrain(terrain_script: GDScript, seed_value: int) -> Node3D:
	"""
	A REAL terrain in the tree on `seed_value`, with the crocodile scene check 2
	needs. `landmark_sites_selfcheck`'s recipe, and both halves of it matter: IN
	THE TREE because `create_chunk` parents its chunk to it and several spawners
	ask that chunk for a global transform, and SEEDED AFTER `add_child` because
	`_ready()` rolls its own seed and would throw an earlier one away.

	It never streams on its own: `_ready` finds no node in group "player", so
	`player` stays null and `_process` returns immediately.
	"""
	var terrain := Node3D.new()
	terrain.set_script(terrain_script)
	terrain.crocodile_scene = load(CROC_SCENE)
	root.add_child(terrain)
	terrain.set_run_seed(seed_value)
	return terrain


# ============================================================================
# CHECK 1 — the table is stable, and its width is not a function of the seed
# ============================================================================

func _check_determinism(terrain_script: GDScript) -> void:
	"""
	Same seed, same table; new seed, the road moves and the HQ does not; and the
	count and the ids are the same in every world.

	THE COUNT IS THE POINT. `waypoint_mask` is one int with one bit per index, so
	a table whose length depended on the seed would mean two peers in one room
	disagreeing about what bit 5 refers to. The road slot count is
	`int(ROAD_TERMINAL_X / WAYPOINT_SPACING)` — two constants and no seed — and
	this is where that argument is turned into a measurement.
	"""
	# THE WIRE WIDTH, PINNED TO THE TABLE. `TerrainWaypoints.WAYPOINT_COUNT` is
	# written out as a literal because GDScript cannot fold
	# `BudapestPlan.WAYPOINTS.size()` into a `const` — so it is a second place to
	# edit, and this is what makes that safe. It bounds `decode_wp`'s index test
	# and both `adopt_waypoint_mask` AND masks, so a count below the real table
	# would silently truncate the crew's found set at the eleventh circle.
	if TerrainWaypoints.WAYPOINT_COUNT != EXPECTED_IDS.size():
		_fail("TerrainWaypoints.WAYPOINT_COUNT is %d but the table has %d rows — the mask "
				% [TerrainWaypoints.WAYPOINT_COUNT, EXPECTED_IDS.size()]
				+ "width and the site table are one fact and they have drifted")

	var first: Array[Dictionary] = []
	for seed_value: int in SEEDS:
		var terrain := _terrain(terrain_script, seed_value)
		var sites: Array[Dictionary] = TerrainWaypoints.waypoint_sites(terrain)
		var again: Array[Dictionary] = TerrainWaypoints.waypoint_sites(terrain)
		if var_to_bytes(sites) != var_to_bytes(again):
			_fail("seed %d: waypoint_sites() asked twice in a row gave two different tables"
					% seed_value)
		if sites.size() != EXPECTED_IDS.size():
			_fail("seed %d: %d waypoints, wanted %d — the mask width is not allowed to "
					% [seed_value, sites.size(), EXPECTED_IDS.size()]
					+ "depend on the seed")
		else:
			for i in sites.size():
				if String(sites[i]["id"]) != EXPECTED_IDS[i]:
					_fail("seed %d: index %d is '%s', wanted '%s' — the index is the wire "
							% [seed_value, i, String(sites[i]["id"]), EXPECTED_IDS[i]]
							+ "bit and the order is a contract")
				var pos: Vector3 = sites[i]["pos"]
				if not is_equal_approx(pos.y, 0.0):
					_fail("seed %d: waypoint %d ('%s') stands at y = %.2f — the world is flat"
							% [seed_value, i, String(sites[i]["id"]), pos.y])
		if first.is_empty():
			first = sites
		else:
			# The HQ hangs off tower_site(), which is a constant for every run that
			# will ever be played; the road hangs off the station cache, which is
			# not. Both directions, so neither can pass vacuously.
			if (first[0]["pos"] as Vector3) != (sites[0]["pos"] as Vector3):
				_fail("the HQ circle moved between seeds %d and %d — tower_site() is a "
						% [SEEDS[0], seed_value] + "constant and nothing may make it a roll")
			var moved := false
			for i in range(ROAD_FIRST, ROAD_LAST + 1):
				if (first[i]["pos"] as Vector3) != (sites[i]["pos"] as Vector3):
					moved = true
			if not moved:
				_fail("every road circle sits on the same metre on seeds %d and %d — the "
						% [SEEDS[0], seed_value]
						+ "sites are not reading the seeded station cache at all")
		terrain.free()
	_check_cache_warmth_cannot_move_a_site(terrain_script)
	print("  %d sites, stable ids and indices on %d seeds; the road moves with the seed, "
			% [EXPECTED_IDS.size(), SEEDS.size()]
			+ "the HQ does not, and a warm station cache moves nothing")
	Sentinel.done("determinism")


func _check_cache_warmth_cannot_move_a_site(terrain_script: GDScript) -> void:
	"""
	THE REGRESSION CONTROL FOR THE WET RE-WALK, and the only assertion in this file
	that can see the defect revmux found in round 1 of PR #364.

	`_road_site` used to clamp its walking index against `terrain.road_k_max` — the
	high-water mark of whatever chunks had streamed — instead of against
	`_road_terminal_k()`. That made a road circle a function of WHEN it was asked:
	cold, the walk stopped at the cache frontier just past T; warm, it kept going
	east. Everything else in this file is blind to it. The two calls above run at
	IDENTICAL cache warmth (the first one's own `_road_extend_to_x` is what warms
	it, and the second grows it no further), so they agree under either clamp;
	check 2 compares chunk signatures, check 3 reads one table per seed, and check
	4 takes the table before it builds anything.

	TWO HALVES, AND BOTH ARE MUTATION-TESTED AGAINST THE PRE-FIX CLAMP:

	  a. THE TEXT. `_road_site`'s body may not mention `road_k_max` at all. It is
	     the `landmark_sites_selfcheck` check-4 idiom — read the function, refuse
	     the thing it must not touch. It cannot pass vacuously: a body that cannot
	     be found fails by name. It reads CODE ONLY, because the docstring names
	     `road_k_max` on purpose (it is the argument for the terminal).
	  b. THE BEHAVIOUR. Ask `_road_site` about a station that is WET at the nominal
	     target, once against a COLD cache and once against one warmed far east of
	     the terminal; the answers must be the same metre, and neither may lie east
	     of the terminal station.

	HALF (b) ONLY WORKS ON THE RIGHT TARGET, and that is a selection rule, not
	luck. Cold, `road_k_max` is `terminal + 1`, so the two clamps can only answer
	differently once the walk steps PAST the terminal — which needs a wet station
	within one `WAYPOINT_RIVER_STEP` of it. The first cut of this control took the
	first wet station anywhere on the road, settled on one ~250 m short of T, and
	measured two identical answers; round 3 of the PR #364 review caught it. The
	sweep below now takes only a wet station STRICTLY inside that window and skips
	a seed that has none. With the window enforced, aliasing the clamp back to the
	cache frontier reds BOTH assertions on seed 1: the cold leg answers x 1451.2
	and the warm leg x 1474.9, BOTH east of a terminal at 1446.5 — which is why
	the east-of-terminal assertion catches each of them, and the two differing
	from each other is what the first assertion catches.

	A WET STATION HAS TO BE FOUND, not assumed — the three CI seeds' roads run
	through dry ground for the last 60 m before T. `CONTROL_SEEDS` is swept until
	one has it, and a sweep that finds none FAILS rather than passing quietly: a
	control nobody can run is not a control.
	"""
	var source: String = FileAccess.get_file_as_string(SOURCE_SCRIPTS[0])
	# CODE ONLY. `_road_site`'s docstring NAMES `road_k_max` — it is the whole
	# argument for why the clamp is the terminal — so a raw text scan would fail on
	# the explanation of the fix. `_code_only` drops the docstring and the comments
	# and leaves the statements, which is what the assertion is about.
	var body: String = _code_only(_function_body(source, "_road_site"))
	if body.strip_edges().is_empty():
		_fail("no `_road_site` in %s — check 1's text control now measures nothing"
				% SOURCE_SCRIPTS[0])
	elif body.contains("road_k_max"):
		_fail("`_road_site` reads `road_k_max` — that is the station cache's high-water "
				+ "mark, a fact about which chunks have streamed, so a site clamped "
				+ "against it is a function of when it was asked. `_road_terminal_k()` "
				+ "is the bound that is a fact about the world")
	for seed_value: int in CONTROL_SEEDS:
		var cold := _terrain(terrain_script, seed_value)
		# Warm exactly as `waypoint_sites()` does, then look for a wet station on
		# the stretch a road waypoint can actually be asked about.
		cold._road_extend_to_x(TerrainWaypoints.WAYPOINT_APPROACH_X, cold.ROAD_TERMINAL_X)
		var terminal: int = cold._road_terminal_k()
		# THE DISCRIMINATING WINDOW, and it is a SELECTION RULE rather than a
		# preference. Cold, `road_k_max` is `terminal + 1` (the extend stops at the
		# first station east of T), so the old clamp and the new one can only answer
		# differently once the walk steps past `terminal` — which needs the target
		# station to be wet within ONE step of it. A wet station anywhere further
		# west is cleared long before either clamp binds, and a control built on one
		# compares two identical answers and proves nothing. So the scan runs
		# backward from `terminal` ITSELF (the single best target: the old cold leg
		# alone lands at `terminal + 1` from there) and stops at
		# `terminal - WAYPOINT_RIVER_STEP`; a seed with no wet station in that window
		# is SKIPPED, not accepted. Round 3 of the PR #364 review is why this is a
		# window and not "the first wet station on the road".
		var wet_x: float = INF
		# STRICTLY INSIDE, and the `+ 1` is the whole assertion. The condition is
		# `k + WAYPOINT_RIVER_STEP > terminal`, so `terminal - WAYPOINT_RIVER_STEP`
		# itself does NOT qualify: from there the walk's second probe is exactly
		# `terminal`, which both clamps allow, so all three legs (new, old-cold,
		# old-warm) land on the same station and the control would pass on the very
		# code it exists to catch. No `maxi` against the road's west end either —
		# station 0 is at x = 0 and the terminal is never below ~240, so that arm
		# could never win. Both found by revmux round 4 of PR #364.
		var floor_k: int = terminal - TerrainWaypoints.WAYPOINT_RIVER_STEP + 1
		for k in range(terminal, floor_k - 1, -1):
			var c: Vector2 = cold._road_station(k).center
			if cold.is_river_at(Vector3(c.x, 0.0, c.y)):
				wet_x = c.x
				break
		if is_inf(wet_x):
			cold.free()
			continue
		var cold_terminal_x: float = cold._road_station(terminal).center.x
		var cold_pos: Vector3 = TerrainWaypoints._road_site(cold, "probe", wet_x)["pos"]
		cold.free()

		var warm := _terrain(terrain_script, seed_value)
		warm._road_extend_to_x(TerrainWaypoints.WAYPOINT_APPROACH_X, warm.ROAD_TERMINAL_X)
		# A frontier far east of the terminal — what an hour of walking toward
		# Budapest leaves behind, and what the old clamp read as permission.
		warm._road_extend_to_x(TerrainWaypoints.WAYPOINT_APPROACH_X, warm.ROAD_TERMINAL_X * 3.0)
		var warm_pos: Vector3 = TerrainWaypoints._road_site(warm, "probe", wet_x)["pos"]
		warm.free()

		if cold_pos != warm_pos:
			_fail("seed %d: a road circle whose target station is wet lands at %s on a cold "
					% [seed_value, str(cold_pos)]
					+ "station cache and at %s on a warm one — the re-walk is reading "
					% str(warm_pos) + "road_k_max, which is a fact about this moment")
		# AND NEITHER ANSWER MAY LEAVE THE ROAD. The terminal station is the last
		# one at or west of ROAD_TERMINAL_X, and past it no spawner keeps a road
		# clearance and the Budapest rect begins — so a walk that ran off the end
		# is the second half of the same defect, and this is the half that does not
		# depend on the two legs disagreeing.
		for leg: Array in [[cold_pos, "cold"], [warm_pos, "warm"]]:
			var at: Vector3 = leg[0]
			if at.x > cold_terminal_x:
				_fail("seed %d: the wet re-walk walked a circle to x %.1f on a %s cache, past "
						% [seed_value, at.x, String(leg[1])]
						+ "the road's terminal station at %.1f — east of T nothing keeps a "
						% cold_terminal_x + "road clearance and the city authors its own")
		# "NOT PAST", never "west of": the backward scan breaks on the first wet
		# index, so every station between it and the terminal is dry and the walk
		# always resolves ON the terminal station. Equality is what the assertion
		# above allows; claiming margin the control never measured is how a log line
		# tells a maintainer something it did not prove.
		print("    the wet re-walk answers %s cold and warm, not past the terminal at %.0f "
				% [str(cold_pos), cold_terminal_x] + "(seed %d, target x %.0f)"
				% [seed_value, wet_x])
		Sentinel.done("cache_warmth")
		return
	_fail("no seed in CONTROL_SEEDS has a WET road station within WAYPOINT_RIVER_STEP of its "
			+ "terminal, which is the only window where the two clamps can answer "
			+ "differently — so the wet re-walk's behavioural control cannot run. Add seeds "
			+ "until one does (a seed whose road merely crosses water somewhere is NOT "
			+ "enough, and is what round 3 of the PR #364 review caught this settling for).")
	Sentinel.done("cache_warmth")


# ============================================================================
# CHECK 2 — the feature costs the chunk's streams nothing
# ============================================================================

func _check_no_draw(terrain_script: GDScript) -> void:
	"""
	Asking "does a waypoint stand here" must not move anything else in the world.

	THE TEXT HALF: the waypoint family carries no `randf` / `randi`, no `hash(`
	and no `scarcity_at`. The first three are the epic's "sites are pure
	arithmetic over already-seeded state"; the last is the scarcity rule — a
	fixed set of eleven places is neither thinned nor unthinned.

	THE BEHAVIOURAL HALF, which is what would catch a draw hidden behind a
	helper: a chunk with NO site is generated twice, once with `spawn_waypoints`
	on and once off, and the two must be byte-identical down to the CROCODILE
	positions. Then the same A/B on a chunk WITH a site, where THREE things are
	asserted and each one is a different promise:

	  * its boxes MUST differ — otherwise the comparator is blind and the
	    site-free half above proves nothing;
	  * its crocodiles must NOT differ — a waypoint appends no footprint, so the
	    crocodile spawner cannot even see it (a landmark's footprint legitimately
	    moves them, which is why that check allows it and this one forbids it);
	  * its `obstacles` must NOT differ — the same promise from the other end,
	    read off the list itself rather than off its consequence.
	"""
	var body := ""
	var unread := ""
	for path: String in SOURCE_SCRIPTS:
		var source: String = FileAccess.get_file_as_string(path)
		if source.is_empty():
			unread = path
			break
		body += source + "\n"
	if not unread.is_empty():
		_fail("could not read %s as text — check 2's text half cannot run" % unread)
	elif not body.contains("spawn_waypoint_in_chunk"):
		_fail("check 2 found no `spawn_waypoint_in_chunk` in %s — the family was renamed "
				% ", ".join(SOURCE_SCRIPTS) + "and this assertion now measures nothing")
	else:
		for forbidden: String in FORBIDDEN:
			if body.contains(forbidden):
				_fail("the waypoint family contains `%s` — the sites are pure arithmetic "
						% forbidden + "over already-seeded state and the ring takes no "
						+ "gradient (see its banner)")

	# A site chunk and a site-free neighbour, both off the first seed's table.
	var probe := _terrain(terrain_script, SEEDS[0])
	var sites: Array[Dictionary] = TerrainWaypoints.waypoint_sites(probe)
	var site_chunk: Vector2i = probe.world_to_chunk(sites[1]["pos"] as Vector3)
	var taken: Dictionary = {}
	for row: Dictionary in sites:
		taken[probe.world_to_chunk(row["pos"] as Vector3)] = true
	var empty_chunk: Vector2i = site_chunk + Vector2i(3, 3)
	while taken.has(empty_chunk):
		empty_chunk += Vector2i(1, 0)
	probe.free()

	var empty_on := _signature(terrain_script, empty_chunk, true)
	var empty_off := _signature(terrain_script, empty_chunk, false)
	if empty_on["boxes"] != empty_off["boxes"] \
			or empty_on["obstacles"] != empty_off["obstacles"] \
			or empty_on["crocs"] != empty_off["crocs"]:
		_fail("chunk %s holds NO waypoint, yet it generates differently with spawn_waypoints "
				% str(empty_chunk) + "on and off — the reverse lookup is taking a draw somewhere")

	var site_on := _signature(terrain_script, site_chunk, true)
	var site_off := _signature(terrain_script, site_chunk, false)
	if site_on["boxes"] == site_off["boxes"]:
		_fail("chunk %s emits the same boxes with spawn_waypoints on and off — either no ring "
				% str(site_chunk) + "was built there or check 2's comparator is blind")
	if site_on["crocs"] != site_off["crocs"]:
		_fail("chunk %s moves its crocodiles when its waypoint is built — the ring appends no "
				% str(site_chunk) + "footprint, so the crocodile spawner must not be able to see it")
	if site_on["obstacles"] != site_off["obstacles"]:
		_fail("chunk %s grows its obstacles list when its waypoint is built — the ring is flat "
				% str(site_chunk) + "and walkable and appends NO footprint (see the family's banner)")
	print("  the waypoint family takes no draw and asks no gradient; a site-free chunk is "
			+ "byte-identical with the rings on and off (crocodiles included)")
	Sentinel.done("no_draw")


func _signature(terrain_script: GDScript, chunk: Vector2i, waypoints_on: bool) -> Dictionary:
	"""
	Generate one chunk in `create_chunk`'s order and return the three signatures
	check 2 compares: `boxes` (the whole visual batch), `obstacles` (the footprint
	list as it stands when the waypoint is done with it) and `crocs` (the bodies,
	which run after and read those footprints).

	NOT `create_chunk` ITSELF, unlike check 4, and for `landmark_sites_selfcheck`'s
	reason: this needs the batch and the obstacle list in hand, which only calling
	the spawners in order can give. Everything the comparison does not need runs
	anyway, so the chunk is the real one.

	The terrain and its scratch chunk go into the tree, because the chest asks its
	parent for a global transform and a tree on `setup()`.
	"""
	var terrain := _terrain(terrain_script, SEEDS[0])
	terrain.spawn_waypoints = waypoints_on
	var platforms: Array = []
	var batch: Array = []
	var body := StaticBody3D.new()
	var obstacles: Array = terrain.spawn_objects_in_chunk(chunk, platforms, batch, body)
	terrain.spawn_biome_content_in_chunk(chunk, obstacles, batch, body)
	var chunk_node := MeshInstance3D.new()
	chunk_node.position = terrain.chunk_to_world(chunk)
	terrain.add_child(chunk_node)
	terrain.spawn_artifact_in_chunk(chunk, chunk_node, obstacles, batch, body)
	terrain.spawn_camp_in_chunk(chunk, chunk_node, obstacles, batch, body)
	TerrainLandmarks.spawn_landmark_in_chunk(terrain, chunk, chunk_node, obstacles, batch, body)
	terrain.spawn_chest_in_chunk(chunk, chunk_node, obstacles, batch, body)
	TerrainWaypoints.spawn_waypoint_in_chunk(terrain, chunk, chunk_node, obstacles, batch, body)
	var croc_parent := MeshInstance3D.new()
	croc_parent.position = terrain.chunk_to_world(chunk)
	terrain.add_child(croc_parent)
	terrain.spawn_crocodiles_in_chunk(chunk, croc_parent, obstacles)
	var crocs := PackedStringArray()
	for child in croc_parent.get_children():
		crocs.append("%s@%s" % [child.name, str((child as Node3D).position)])
	var out := {
		"boxes": var_to_bytes(batch),
		"obstacles": var_to_bytes(obstacles),
		"crocs": crocs,
	}
	body.free()
	terrain.free()  # frees the scratch chunk and the croc parent with it
	return out


# ============================================================================
# CHECK 3 — nowhere a circle must not stand
# ============================================================================

func _check_legality(terrain_script: GDScript) -> void:
	"""
	Every site of every seed, against the predicates the GAME asks — never against
	a copy of them written here.

	THE ROAD'S CIRCLES may not be wet (a station in a band would put the ring
	under a field bridge's deck, or in the water beside it) and may not be inside
	the Budapest rect (the city authors its own five). The centreline is clear of
	blocks by construction — every field spawner keeps a road clearance — which is
	what lets a road ring get away with appending no footprint.

	THE CITY'S FIVE must be inside the rect, dry, off both `PLATEAUS` and their
	ramps, clear of every `SLOTS` disc, clear of every `block_wing()` a 2.6 m ring
	could reach, and ON a street line within `AVENUE_HALF_WIDTH`. The wing and
	plateau tests are measured with the ring's RADIUS, not its centre: the promise
	is that no part of the circle is inside somebody's facade or inside a hill.

	THE HQ'S is outside the shell's outer wall and within `HQ_DOOR_MAX` of the
	door trigger, so it is the thing you stand on when you come out of the
	building rather than a circle round the back of it.

	FOUR MUTATION CONTROLS, each driving one of those predicates with a
	deliberately illegal point, because a predicate that always answers false
	would make every assertion above pass in silence.
	"""
	var wing_clearance: float = TerrainWaypoints.RING_RADIUS
	for seed_value: int in SEEDS:
		var terrain := _terrain(terrain_script, seed_value)
		var sites: Array[Dictionary] = TerrainWaypoints.waypoint_sites(terrain)
		for i in sites.size():
			var id: String = String(sites[i]["id"])
			var pos: Vector3 = sites[i]["pos"]
			if i == 0:
				var tower: Vector3 = terrain.tower_site()
				if absf(pos.x - tower.x) <= TowerShell.OUTER_HALF:
					_fail("seed %d: the HQ circle is at x %.1f, inside the shell's outer wall "
							% [seed_value, pos.x] + "at %.1f" % (tower.x + TowerShell.OUTER_HALF))
				var door: Dictionary = TowerShell.door_trigger_box()
				var door_world: Vector3 = tower + (door["pos"] as Vector3)
				var gap: float = Vector2(pos.x - door_world.x, pos.z - door_world.z).length()
				if gap > HQ_DOOR_MAX:
					_fail("seed %d: the HQ circle is %.1f m from the doorway, wanted <= %.1f — "
							% [seed_value, gap, HQ_DOOR_MAX] + "it is the door's circle")
			elif i <= ROAD_LAST:
				if terrain.is_river_at(pos):
					_fail("seed %d: road circle '%s' at %s is in a river band — the wet "
							% [seed_value, id, str(pos)] + "re-walk ran out of tries")
				if terrain.in_budapest(pos.x, pos.z):
					_fail("seed %d: road circle '%s' at %s is inside the Budapest rect, where "
							% [seed_value, id, str(pos)] + "the plan authors its own five")
			else:
				_check_city_site(seed_value, id, pos, wing_clearance)
		terrain.free()

	# --- The controls. Each one is the SAME predicate the loop above trusted,
	# handed a point that must be refused.
	var control := _terrain(terrain_script, SEEDS[0])
	var wet: Vector3 = _find_wet_point(control)
	if wet.y < 0.0:
		_fail("check 3 found no river band within 3 km of the origin on seed %d — its wet "
				% SEEDS[0] + "control cannot run and the road's river test is unproven")
	elif not control.is_river_at(wet):
		_fail("check 3's wet control at %s is not reported wet — is_river_at() answers false "
				% str(wet) + "for everything and every road assertion above is vacuous")
	control.free()

	var slot: Dictionary = BudapestPlan.SLOTS[0]
	var slot_pos: Vector3 = slot["pos"]
	if not _inside_a_slot(slot_pos):
		_fail("check 3's slot control — the centre of '%s' itself — is not reported inside a "
				% String(slot["id"]) + "SLOTS disc, so the city sites' disc test is vacuous")
	var wing: Rect2 = BudapestPlan.block_wing(Vector2i(6, 6), 0)
	if _wing_gap(wing.get_center()) > 0.0:
		_fail("check 3's wing control — the centre of a real block_wing rect — measures a "
				+ "positive gap to that wing, so the city sites' facade test is vacuous")
	# THE HILL CONTROL, and it is the one this check most needs. `_plateau_gap` is
	# the only predicate in check 3 that does not go through a shipped function —
	# it reads the `PLATEAUS` const and re-derives rect distance — so an emptied or
	# restructured table would make its loop iterate nothing and pass every circle
	# in silence. A point inside Castle Hill is also a point every OTHER assertion
	# here waves through: it is dry, outside every SLOTS disc, on a street line,
	# and `_wing_gap` answers INF because `block_buildable()` refuses plateau cells
	# and the sweep skips them. (Found by revmux round 2 of PR #364.)
	var hill: Rect2 = (BudapestPlan.PLATEAUS[0] as Dictionary)["rect"]
	if _plateau_gap(hill.get_center()) > 0.0:
		_fail("check 3's hill control — the centre of a real PLATEAUS rect — measures a "
				+ "positive gap to that plateau, so the city sites' hill test is vacuous")
	elif _wing_gap(hill.get_center()) <= TerrainWaypoints.RING_RADIUS:
		_fail("check 3's hill control stands inside a block_wing, so the facade test would "
				+ "catch it anyway and the hill test is still unproven — move the control "
				+ "to a plateau cell the block grid really does leave empty")

	print("  every site of %d seeds clears the river, the rect, the discs, the hills, the "
			% SEEDS.size() + "facades and the wall; 4 mutation controls refused")
	Sentinel.done("legality")


func _check_city_site(seed_value: int, id: String, pos: Vector3, clearance: float) -> void:
	"""One authored city circle against the plan's own predicates. Split out only
	because the loop above was doing three jobs."""
	if not BudapestPlan.contains(pos.x, pos.z):
		_fail("seed %d: city circle '%s' at %s is outside the city rect"
				% [seed_value, id, str(pos)])
	if BudapestPlan.danube_wet(pos.x, pos.z):
		_fail("seed %d: city circle '%s' at %s is in the Danube" % [seed_value, id, str(pos)])
	if _inside_a_slot(pos):
		_fail("seed %d: city circle '%s' at %s is inside a SLOTS disc — a landmark's stone "
				% [seed_value, id, str(pos)] + "would stand in the ring")
	# THE PLATEAUS, AND THE FACADE TEST BELOW CANNOT STAND IN FOR THEM. `_wing_gap`
	# skips every cell `block_buildable()` refuses, and that predicate refuses every
	# plateau and ramp cell — so a circle buried in Castle Hill's 30 m of solid
	# stone measures an INF gap to the nearest facade and sails through. It would
	# also be a street crossing, dry and clear of every disc: every other assertion
	# here would pass it. SECTION 7b's banner promises all five are "off both
	# PLATEAUS", so this is where that promise is measured.
	# (Found by revmux review of PR #364; nothing ships on a hill, this is the
	# assertion the promise was missing.)
	var hill: float = _plateau_gap(Vector2(pos.x, pos.z))
	if hill <= clearance:
		_fail("seed %d: city circle '%s' at %s is %.1f m from a plateau or its ramp, wanted "
				% [seed_value, id, str(pos), hill]
				+ "> %.1f — a ring on a hill stands on its lid, not on the flat world"
				% clearance)
	var gap: float = _wing_gap(Vector2(pos.x, pos.z))
	if gap <= clearance:
		_fail("seed %d: city circle '%s' at %s is %.1f m from a block_wing, wanted > %.1f — "
				% [seed_value, id, str(pos), gap, clearance]
				+ "part of the ring would be inside a facade")
	# ON a street line: the nearest grid line either way, and the crossing is what
	# makes the two clearances above true by construction rather than by luck.
	var k: int = roundi((pos.x - BudapestPlan.GATE.x) / BudapestPlan.STREET_PITCH)
	var m: int = roundi((pos.z - BudapestPlan.GATE.z) / BudapestPlan.STREET_PITCH)
	var off_x: float = absf(pos.x - BudapestPlan.street_x(k))
	var off_z: float = absf(pos.z - BudapestPlan.street_z(m))
	if minf(off_x, off_z) > BudapestPlan.AVENUE_HALF_WIDTH:
		_fail("seed %d: city circle '%s' at %s is %.1f m off the nearest street line, wanted "
				% [seed_value, id, str(pos), minf(off_x, off_z)]
				+ "<= %.1f — the streets are the only ground the plan keeps clear"
				% BudapestPlan.AVENUE_HALF_WIDTH)


func _inside_a_slot(pos: Vector3) -> bool:
	"""Is this XZ inside any authored landmark's declared disc?"""
	for row_v: Variant in BudapestPlan.SLOTS:
		var row: Dictionary = row_v
		var at: Vector3 = row["pos"]
		if Vector2(pos.x - at.x, pos.z - at.z).length() < float(row["radius"]):
			return true
	return false


func _plateau_gap(p: Vector2) -> float:
	"""
	Distance from `p` to the nearest `PLATEAUS` rect or ramp, or 0 when it is inside
	one. Check 3's hill test, and its mutation control below drives this same
	function — which is why it is a function and not six lines inlined in the loop.
	"""
	var best: float = INF
	for row_v: Variant in BudapestPlan.PLATEAUS:
		var row: Dictionary = row_v
		for rect: Rect2 in [row["rect"] as Rect2, row["ramp"] as Rect2]:
			var near := Vector2(clampf(p.x, rect.position.x, rect.end.x),
					clampf(p.y, rect.position.y, rect.end.y))
			best = minf(best, p.distance_to(near))
	return best


func _wing_gap(p: Vector2) -> float:
	"""
	Distance from `p` to the nearest `block_wing()` rect of the nine cells around
	it, or 0 when it is inside one.

	Nine cells because a point on a street line belongs to the cell east/south of
	it by `block_cell`'s convention, so its neighbours' wings are the near ones.
	"""
	var home: Vector2i = BudapestPlan.block_cell(p.x, p.y)
	var best: float = INF
	for dx in [-1, 0, 1]:
		for dz in [-1, 0, 1]:
			var cell := home + Vector2i(dx, dz)
			if not BudapestPlan.block_buildable(cell):
				continue
			for side in 4:
				var r: Rect2 = BudapestPlan.block_wing(cell, side)
				var near := Vector2(clampf(p.x, r.position.x, r.end.x),
						clampf(p.y, r.position.y, r.end.y))
				best = minf(best, p.distance_to(near))
	return best


func _find_wet_point(terrain: Node3D) -> Vector3:
	"""A field point inside a river band within 3 km of the origin, or y = -1 when
	this world has none. Check 3's wet control."""
	for cx in range(-60, 61):
		for cz in range(-60, 61):
			var world: Vector3 = terrain.chunk_to_world(Vector2i(cx, cz))
			if terrain.in_budapest(world.x, world.z):
				continue
			if terrain.is_river_at(world):
				return world
	return Vector3(0.0, -1.0, 0.0)


# ============================================================================
# CHECK 4 — the rings are built by the shipped pipeline
# ============================================================================

func _check_built(terrain_script: GDScript) -> void:
	"""
	THE SITES ARE WALKED. Every one of the eleven chunks is built through the
	SHIPPED `create_chunk` — not a hand-rolled spawner order, which is the mistake
	`landmark_sites_selfcheck._build_every_site` documents at length — and must
	come out holding exactly one marker in group "waypoint" with the right
	`index`, carrying a beam that is a real mesh and is HIDDEN. Nothing in this
	bead shows a beam; child .2 is what lights one, and a beam that shipped
	visible would be eleven pillars of light standing over an inert feature.

	THE BILL is measured separately, through a direct call on an empty batch,
	because `create_chunk`'s batch is full of everything else: one ring costs
	exactly `RING_BOX_COUNT` boxes, not one of them colliding (you walk onto a
	waypoint — a collider would be a kerb), and zero entries of `obstacles`.
	"""
	var terrain := _terrain(terrain_script, SEEDS[0])
	var sites: Array[Dictionary] = TerrainWaypoints.waypoint_sites(terrain)
	for i in sites.size():
		var chunk: Vector2i = terrain.world_to_chunk(sites[i]["pos"] as Vector3)
		terrain.create_chunk(chunk)
		var chunk_node: Node3D = terrain.active_chunks.get(chunk)
		if chunk_node == null:
			_fail("create_chunk built nothing for chunk %s, where waypoint %d ('%s') stands"
					% [str(chunk), i, String(sites[i]["id"])])
			continue
		var markers: Array[Node] = []
		for child in chunk_node.get_children():
			if child is Node3D and child.is_in_group(TerrainWaypoints.WAYPOINT_GROUP):
				markers.append(child)
		if markers.size() != 1:
			_fail("chunk %s holds %d waypoint markers, wanted 1 — waypoint %d ('%s') stands "
					% [str(chunk), markers.size(), i, String(sites[i]["id"])]
					+ "there and nothing else does")
			continue
		var marker: Node3D = markers[0]
		if int(marker.get_meta("index", -1)) != i:
			_fail("the marker in chunk %s carries index %d, wanted %d — the meta IS the wire "
					% [str(chunk), int(marker.get_meta("index", -1)), i]
					+ "bit child .2 reads")
		var beam: MeshInstance3D = null
		for child in marker.get_children():
			if child is MeshInstance3D:
				beam = child
		if beam == null:
			_fail("waypoint %d ('%s') has no beam — child .2 has nothing to light"
					% [i, String(sites[i]["id"])])
		elif beam.visible:
			_fail("waypoint %d ('%s') ships its beam VISIBLE — this bead lights nothing, and "
					% [i, String(sites[i]["id"])] + "an inert circle with a pillar of light "
					+ "over it is a promise the game cannot keep yet")
		elif beam.mesh == null:
			_fail("waypoint %d ('%s') has a beam with no mesh" % [i, String(sites[i]["id"])])

	# --- The bill, on an empty batch.
	var batch: Array = []
	var obstacles: Array = []
	var body := StaticBody3D.new()
	var host := MeshInstance3D.new()
	terrain.add_child(host)
	var first_chunk: Vector2i = terrain.world_to_chunk(sites[0]["pos"] as Vector3)
	TerrainWaypoints.spawn_waypoint_in_chunk(terrain, first_chunk, host, obstacles, batch, body)
	if batch.size() != TerrainWaypoints.RING_BOX_COUNT:
		_fail("one ring emitted %d boxes, wanted %d — the disc plus its %d studs"
				% [batch.size(), TerrainWaypoints.RING_BOX_COUNT, TerrainWaypoints.STUD_COUNT])
	if not obstacles.is_empty():
		_fail("one ring appended %d obstacles — a waypoint is flat, walkable paint and "
				% obstacles.size() + "appends NO footprint (see the family's banner)")
	if body.get_child_count() != 0:
		_fail("one ring added %d collision shapes — every box is `collide = false`, or the "
				% body.get_child_count() + "circle is a kerb you trip over")
	body.free()
	terrain.free()
	print("  all %d sites build one marker, one hidden beam and exactly %d non-colliding "
			% [sites.size(), TerrainWaypoints.RING_BOX_COUNT]
			+ "boxes through create_chunk, and no footprint")
	Sentinel.done("built")


# ============================================================================
# CHECK 5 — the circle is FOUND, and the whole crew's beam follows the mask
# ============================================================================
#
# Bead `godot-test1-sc6.2`. Four things, in the order a find actually travels:
#
#   a. THE MASK on a real `player.tscn` — a bit is set once, a repeat answers
#      false (which is what makes the hub's enter edge free to fire as often as
#      the player wanders on and off), an out-of-range index sets nothing, and
#      `adopt_waypoint_mask` ORs rather than assigns and masks the wire's integer
#      down to the circles that exist.
#   b. THE REPAIR PACKET's optional field: `decode_room` with no `w` reads it as
#      0 and KEEPS THE PACKET — `landmark_progress_selfcheck` check 4's argument,
#      and mixed builds are real (`build_version` refuses to reload a peer that is
#      in a room), so a master without the field must still repair the cells.
#   c. END TO END THROUGH THE SHIPPED `_receive_wp`: one relay-shaped packet in at
#      the room's front door, and out the other end a bit on the player AND a LIT
#      BEAM on a marker `create_chunk` really built. Never around the functions —
#      a check that set the bit by hand would pass with the verb unwired.
#   d. THE ENTER EDGE: standing the hero on a circle finds it, and walking away
#      re-arms the latch past the dead band.

func _check_discovery(terrain_script: GDScript) -> void:
	"""The mask, the optional repair field, the verb and the enter edge."""
	# --- a. THE MASK, on the shipped hero.
	var player: Node = load(PLAYER_SCENE).instantiate()
	root.add_child(player)
	await process_frame
	player.waypoint_mask = 0
	if not player.activate_waypoint(3):
		_fail("activate_waypoint(3) refused a circle nobody had found")
	if player.waypoint_mask != 1 << 3:
		_fail("activate_waypoint(3) left the mask at %d, wanted bit 3 alone"
				% player.waypoint_mask)
	if player.activate_waypoint(3):
		_fail("activate_waypoint(3) reported a SECOND find of the same circle — the hub "
				+ "would pop a card and publish a verb on every lap of the ring")
	for illegal: int in [-1, TerrainWaypoints.WAYPOINT_COUNT, 64]:
		if player.activate_waypoint(illegal):
			_fail("activate_waypoint(%d) accepted an index off the table" % illegal)
	if player.waypoint_mask != 1 << 3:
		_fail("an out-of-range activate_waypoint moved the mask to %d" % player.waypoint_mask)

	# ORs, never assigns — a stale repair packet may not un-find anything...
	player.adopt_waypoint_mask(1 << 1)
	if player.waypoint_mask != (1 << 3) | (1 << 1):
		_fail("adopt_waypoint_mask ASSIGNED instead of OR-ing: %d" % player.waypoint_mask)
	player.adopt_waypoint_mask(0)
	if player.waypoint_mask != (1 << 3) | (1 << 1):
		_fail("adopt_waypoint_mask(0) un-found a circle — the set is add-only")
	# ...and the AND is the trust boundary's second half: a peer on a build with a
	# twelfth circle sends a twelfth bit, and it must not land in a mask whose
	# consumers only know eleven.
	player.adopt_waypoint_mask(-1)
	var full: int = (1 << TerrainWaypoints.WAYPOINT_COUNT) - 1
	if player.waypoint_mask != full:
		_fail("adopt_waypoint_mask(-1) left %d, wanted the %d legal bits — the mask is "
				% [player.waypoint_mask, TerrainWaypoints.WAYPOINT_COUNT]
				+ "not range-masked on the way in")
	player.waypoint_mask = 0

	# --- b. A MASTER THAT HAS NEVER HEARD OF WAYPOINTS still repairs the cells.
	var legacy: Dictionary = MpCodec.decode_room(
			{"t": "room", "cap": ["teibi"], "cd": 0.0, "co": 0})
	if legacy.is_empty():
		_fail("decode_room DROPPED a room packet with no `w` — an older master's repair "
				+ "channel dies over a field it has never heard of")
	elif int(legacy.get("w", -1)) != 0:
		_fail("decode_room read a missing `w` as %s, wanted 0" % str(legacy.get("w", null)))
	elif (legacy["cap"] as Array).size() != 1:
		_fail("decode_room lost the captive set while reading a packet with no `w`")

	# --- c. END TO END. One chunk built by the shipped pipeline, one room, one
	# packet through the shipped receiver, and the beam must flip.
	#
	# ONE TERRAIN IN THE GROUP FIRST. Checks 1 and 3 stand terrains up on several
	# seeds and leave them in the tree, and this is the first check whose SUBJECT
	# resolves the terrain by group the way the game does (`waypoint_hub._scan`) —
	# so a stray on another seed would hand the hub a different site table than the
	# one asserted against here, and the enter edge would read as broken.
	for stray in get_nodes_in_group("terrain"):
		(stray as Node).queue_free()
		(stray as Node).remove_from_group("terrain")
	var terrain := _terrain(terrain_script, SEEDS[0])
	# THE TERRAIN MUST NOT STREAM. `_terrain()`'s docstring notes it stays inert
	# because nothing is in group "player" — and this check puts a real hero there,
	# which would have it build a hundred chunks round the origin on the next
	# frame. Nothing here needs streaming: the one chunk under test is built by
	# hand through `create_chunk`, exactly as check 4 builds all eleven.
	terrain.set_process(false)
	var sites: Array[Dictionary] = TerrainWaypoints.waypoint_sites(terrain)
	terrain.create_chunk(terrain.world_to_chunk(sites[0]["pos"] as Vector3))
	var beam: MeshInstance3D = _beam_for(0)
	var hub: Node = WaypointHub.new()
	root.add_child(hub)
	var mp: Node = MPManager.new()
	root.add_child(mp)

	if beam == null:
		_fail("check 5 found no beam for waypoint 0 — create_chunk built no marker")
	else:
		hub._tick()
		if beam.visible:
			_fail("the beam of an UNFOUND circle is lit — the hub paints from the mask, "
					+ "and an unfound one is dark")
		# THE RELAY'S SPELLING, deliberately: `i` as a float is what
		# `JSON.parse_string` hands back, so this packet is the shape a real find
		# arrives in when the sender's ICE is still negotiating.
		mp._receive_wp("someoneelse", {"t": "wp", "i": 0.0})
		if player.waypoint_mask & 1 == 0:
			_fail("a `wp` through the shipped _receive_wp never reached the player's mask "
					+ "(mask %d) — the room cannot share a find" % player.waypoint_mask)
		hub._tick()
		if not beam.visible:
			_fail("a teammate's find did not light the beam — the hub is the ONE writer "
					+ "of every beam and a relayed bit must reach it")

	# --- d. THE ENTER EDGE. The hero walks onto circle 1 and finds it; walking
	# clear past the dead band re-arms the latch for the next approach.
	player.global_position = sites[1]["pos"] as Vector3
	hub._tick()
	if player.waypoint_mask & (1 << 1) == 0:
		_fail("standing the hero on circle 1 did not find it — the enter edge is the "
				+ "whole of the discovery")
	if hub.standing_on() != 1:
		_fail("standing_on() is %d with the hero on circle 1 — bead .4's panel opens on "
				% hub.standing_on() + "this")
	player.global_position = (sites[1]["pos"] as Vector3) + Vector3(
			TerrainWaypoints.RING_RADIUS + WaypointHub.LEAVE_PAD + 5.0, 0.0, 0.0)
	hub._tick()
	if hub.standing_on() != -1:
		_fail("standing_on() is still %d with the hero well past LEAVE_PAD — the latch "
				% hub.standing_on() + "never re-arms and the next approach is dead")

	mp.queue_free()
	hub.queue_free()
	player.queue_free()
	terrain.free()
	print("  the mask is add-only and range-masked, a room packet with no `w` still "
			+ "repairs, a relayed find lights the beam through the shipped verb, and "
			+ "the enter edge finds and re-arms")
	Sentinel.done("discovery")


func _beam_for(index: int) -> MeshInstance3D:
	"""
	The beam of the built marker carrying `index`, or null.

	Found the way `waypoint_hub` finds it — by group and by the family's own
	`WAYPOINT_BEAM_NAME` — so a rename that broke the hub breaks this too rather
	than leaving the check quietly looking at a different node.
	"""
	for node in get_nodes_in_group(TerrainWaypoints.WAYPOINT_GROUP):
		var marker := node as Node3D
		if marker == null or int(marker.get_meta("index", -1)) != index:
			continue
		return marker.get_node_or_null(
				NodePath(TerrainWaypoints.WAYPOINT_BEAM_NAME)) as MeshInstance3D
	return null
